import React, { useState, useEffect, useRef } from 'react';
import axios from 'axios';
import Footer from '../../components/DocumentGeneration/Footer'
import DocHeader from '../../components/DocumentGeneration/DocHeader'
import { useSelector } from 'react-redux';
import { useParams } from 'react-router-dom';
import { useReactToPrint } from 'react-to-print';

const DocumentPage = () => {
  const userClauses = useSelector((state) => state.form.clauses);
  const [content, setContent] = useState({ format: '', clauses: [], footer: '' }); // Initialize with default structure
  const params = useParams();
  const [isLoading, setLoading] = useState(false);
  const contentToPrint = useRef(null);

  const handlePrint = useReactToPrint({
    content: () => contentToPrint.current,
    documentTitle: params.name,
    removeAfterPrint: true,
  });

  useEffect(() => {
    const fetchAgreement = async () => {
      try {
        setLoading(true);
        const response = await axios.post('/api/v1/model/generate', {
          selectedFormat: params.name,
          userClauses
        });
        setTimeout(() => {
          const parsedContent = JSON.parse(response.data.doc);
          setContent(parsedContent);
        }, 3000); // 1 second delay
      } catch (error) {
        console.error('Error fetching agreement content:', error);
      } finally {
        setLoading(false);
      }
    };

    fetchAgreement();
  }, [userClauses, params.name]);

  if (isLoading) {
    return (
      <div className='min-h-screen lg:ms-4 md:pb-4 md:shadow-md bg-base-100 flex flex-col justify-center items-center gap-2'>
        <p className='text-center text-red-900 font-bold px-4'>
          The following content has been automatically generated by an AI system and should be used for informational purposes only. We cannot guarantee the accuracy, completeness, or timeliness of the information provided. Any actions taken based on this content are at your own risk.
        </p>
        <span className="loading loading-dots loading-lg"></span>
      </div>
    )
  }

  setTimeout(() => {
    if (content.clauses.length === 0) {
      return <p className='text-center'>We are currently overloaded. Please try again later.</p>;
    }
  }, 2000)

  return (
    <div className="min-h-screen lg:ms-4 md:pb-4 md:shadow-md bg-base-100">
      <DocHeader handlePrint={handlePrint} />
      <div style={{ padding: '20px', fontFamily: 'Arial, sans-serif' }} ref={contentToPrint}>
        <h1 className='text-center text-lg font-bold'>{params.name}</h1>
        <div className='my-3 mx-4'>
          {Object.entries(content?.clauses).map(([key, value], index) => (
            <div key={index}>
              <h3 className="my-2">{value.clause_heading}</h3>
              <p className="my-2">{value.clause_content}</p>
            </div>
          ))}
        </div>
        <div className='my-2 mx-4'>{content?.footer}</div>
      </div>
      <Footer />
    </div>
  );
};

export default DocumentPage;