import React, { useState, useEffect, useRef } from 'react';
import axios from 'axios';
import Footer from '../../components/DocumentGeneration/Footer';
import DocHeader from '../../components/DocumentGeneration/DocHeader';
import { useSelector } from 'react-redux';
import { useParams } from 'react-router-dom';
import { useReactToPrint } from 'react-to-print';

const DocumentPage = () => {
  const userClauses = useSelector((state) => state.form.clauses);
  const [content, setContent] = useState({ format: '', clauses: {}, footer: '' });
  const [isLoading, setLoading] = useState(false);
  const params = useParams();
  const contentToPrint = useRef(null);

  const handlePrint = useReactToPrint({
    content: () => contentToPrint.current,
    documentTitle: params.name,
    removeAfterPrint: true,
  });

  useEffect(() => {
    const fetchAgreement = async () => {
      try {
        setLoading(true);
        const response = await axios.post('/api/v1/model/generate', {
          selectedFormat: params.name,
          userClauses,
        });

        const parsedContent = JSON.parse(response.data.doc);
        setContent(parsedContent);
      } catch (error) {
        console.error('Error fetching agreement content:', error);
      } finally {
        setLoading(false);
      }
    };

    fetchAgreement();
  }, [userClauses, params.name]);

  if (isLoading) {
    return (
      <div className="min-h-screen lg:ms-4 md:pb-4 md:shadow-md bg-base-100 flex flex-col justify-center items-center gap-2">
        <p className="text-center text-red-900 font-bold px-4">
          The following content has been automatically generated by an AI system and should be used for informational purposes only. We cannot guarantee the accuracy, completeness, or timeliness of the information provided. Any actions taken based on this content are at your own risk.
        </p>
        <span className="loading loading-dots loading-lg"></span>
      </div>
    );
  }

  return (
    <div className="min-h-screen lg:ms-4 md:pb-4 md:shadow-md bg-base-100">
      <DocHeader handlePrint={handlePrint} />
      
      <div
        style={{ padding: '20px', fontFamily: 'Arial, sans-serif' }}
        ref={contentToPrint}
      >
        <h1 className="text-center text-lg font-bold mb-4">{params.name}</h1>

        {/* Fallback message if no clauses */}
        {!isLoading && Object.keys(content?.clauses || {}).length === 0 && (
          <p className="text-center text-red-500 font-semibold">
            We are currently overloaded. Please try again later.
          </p>
        )}

        {/* Render clauses */}
        {Object.entries(content?.clauses || {}).map(([key, value], index) => (
          <div key={index} className="mb-3">
            <h3 className="font-semibold capitalize">{key.replace(/_/g, ' ')}</h3>
            <p>{value}</p>
          </div>
        ))}

        {/* Footer */}
        {content?.footer && (
          <div className="mt-6 border-t pt-3">{content.footer}</div>
        )}
      </div>

      <Footer />
    </div>
  );
};

export default DocumentPage;